import os
from typing import Literal, List, Final

CAPTION: Final[str] = "<CAPTION>"
DETAILED_CAPTION: Final[str] = "<DETAILED_CAPTION>"
MORE_DETAILED_CAPTION: Final[str] = "<MORE_DETAILED_CAPTION>"
OD: Final[str] = "<OD>"
OCR: Final[str] = "<OCR>"
OCR_WITH_REGION: Final[str] = "<OCR_WITH_REGION>"
CAPTION_TO_PHRASE_GROUNDING: Final[str] = "<CAPTION_TO_PHRASE_GROUNDING>"
DENSE_REGION_CAPTION: Final[str] = "<DENSE_REGION_CAPTION>"
REGION_PROPOSAL: Final[str] = "<REGION_PROPOSAL>"
REFERRING_EXPRESSION_SEGMENTATION: Final[str] = "<REFERRING_EXPRESSION_SEGMENTATION>"
REGION_TO_SEGMENTATION: Final[str] = "<REGION_TO_SEGMENTATION>"
OPEN_VOCABULARY_DETECTION: Final[str] = "<OPEN_VOCABULARY_DETECTION>"
REGION_TO_CATEGORY: Final[str] = "<REGION_TO_CATEGORY>"
REGION_TO_DESCRIPTION: Final[str] = "<REGION_TO_DESCRIPTION>"


TASK_TYPES: Final[List[str]] = [
    CAPTION,
    DETAILED_CAPTION,
    MORE_DETAILED_CAPTION,
    OD,
    OCR,
    OCR_WITH_REGION,
    CAPTION_TO_PHRASE_GROUNDING,
    DENSE_REGION_CAPTION,
    REGION_PROPOSAL,
    REFERRING_EXPRESSION_SEGMENTATION,
    REGION_TO_SEGMENTATION,
    OPEN_VOCABULARY_DETECTION,
    REGION_TO_CATEGORY,
    REGION_TO_DESCRIPTION
]